export const defaultActivities = [
  { name: "Home Improvement", isForGoodweather: false, id: "17e172df8bb" },
  { name: "Virtual Museum Tours", isForGoodweather: false, id: "617e172df8b" },
  { name: "Puzzle Solving", isForGoodweather: false, id: "d617e172df8" },
  { name: "Arts and Crafts", isForGoodweather: false, id: "fd617e172df" },
  { name: "Reading", isForGoodweather: false, id: "7fd617e172d" },
  { name: "Cooking or Baking", isForGoodweather: false, id: "77fd617e172" },
  { name: "Board Games", isForGoodweather: false, id: "377fd617e17" },
  { name: "Indoor Movie Marathon", isForGoodweather: false, id: "1377fd617e1" },
  { name: "Stargazing", isForGoodweather: true, id: "b1377fd617e" },
  { name: "Canoeing ", isForGoodweather: true, id: "ab1377fd617" },
  {
    name: "Outdoor Yoga or Exercise",
    isForGoodweather: true,
    id: "aab1377fd61",
  },
  { name: "Barbecue or Cookout:", isForGoodweather: true, id: "9aab1377fd6" },
  { name: "Gardening", isForGoodweather: true, id: "a9aab1377fd" },
  { name: "Beach Day", isForGoodweather: true, id: "6a9aab1377f" },
  { name: "Outdoor Sports", isForGoodweather: true, id: "c6a9aab1377" },
  { name: "Cycling", isForGoodweather: true, id: "bc6a9aab137" },
  { name: "Hiking", isForGoodweather: true, id: "abc6a9aab13" },
  { name: "Picnic in the Park", isForGoodweather: true, id: "6abc6a9aab1" },
];
